rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - 2.3.0
before_install:
  - gem update bundler
before_script:
  - bundle install --gemfile=examples/rails4_root/Gemfile
  - bundle install --gemfile=examples/sinatra_root/Gemfile
script:
  - "bundle exec rake"
  - "bundle exec spec spec"
branches:
  only:
    - master
